- name: Install Docker and Python3
  hosts: sn
  become: true
  tasks:
    - name: Copy the Docker installation script to the remote machine
      copy:
        src: scriptd.sh
        dest: /home/ubuntu/scriptd.sh
        mode: '0755'

    - name: Run the Docker installation script
      shell: /home/ubuntu/scriptd.sh

    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv  # Required for creating virtual environments
        state: present
        update_cache: yes

    - name: Create a virtual environment for Python
      command: python3 -m venv /home/ubuntu/venv

    - name: Install Docker Python module inside the virtual environment
      shell: /home/ubuntu/venv/bin/pip install docker-py

    - name: Verify docker-py installation
      shell: /home/ubuntu/venv/bin/python -m pip show docker-py

