---
- name: Install kubectl
  hosts: jen
  become: true
  tasks:
    - name: Copy the kubectl install script to the remote server
      copy:
        src: scriptk.sh
        dest: /home/ubuntu/scriptk.sh
        mode: '0777'

    - name: Run the kubectl install script
      shell: /home/ubuntu/scriptk.sh
